version: "3"

services:
  #Instalo una base de datos mysql 
  bbdd_mysql:
    image: mysql:8
    environment:
    #Envio las variables de entorno que configuran la base de datos
      - MYSQL_DATABASE=hojas_de_vida
      - MYSQL_ROOT_PASSWORD=mipassword
      - MYSQL_USER=miusuario
      - MYSQL_PASSWORD=mipassword
    volumes:
    #Defino un volumen para persistir la informacion
      - ./volumenes/mysql:/var/lib/mysql
    expose:
      - 3307
    ports:
      - 3307:3307
    restart: always

  #Instalo el administrador phpmyadmin para gestionar la base de datos
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - MYSQL_USER=miusuario
      - MYSQL_PASSWORD=mipassword
    ports:
     - 8080:80
  #Enlazo con el servicio de base de datos
    links: 
      - bbdd_mysql:db
    
  #Instalo un servidor apache personalizado con buid para exponer el servicio web e interpretar php
  servidorweb_php:
    build: .
    volumes:
      # Monto los archivos de funcionamiento de la página dentro del contenedor
      - ./hojaDeVida/:/var/www/html
    expose:
      - 80
    ports:
      - 80:80
    #Enlazo con el servicio de base de datos
    links: 
      - bbdd_mysql
    restart: always
